name: h3_common
description: The package provides Dart version of the H3 Core library, a hexagon-based geographic grid system
version: 0.6.1
homepage: https://github.com/festelo/h3_dart

environment:
  sdk: ">=2.14.0 <3.0.0"

dev_dependencies:
  test: ^1.22.2
  lints: ^2.0.0