name: example
description: An absolute bare-bones web app.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.15.1 <3.0.0'


dependencies:
  h3_web:
    path: ..

dev_dependencies:
  build_runner: ^2.3.3
  build_web_compilers: ^3.2.7
  lints: ^2.0.1
  webdev: ^2.7.12
