name: h3_ffi
description: The package provides Dart version of the H3 Core library, a hexagon-based geographic grid system
version: 0.6.0-dev
homepage: https://github.com/festelo/h3_dart

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  ffi: ^2.0.1
  path: ^1.8.1
  h3_common: ^0.6.0-dev

dev_dependencies:
  test: ^1.21.2
  lints: ^2.0.0
  ffigen: ^6.0.1
  collection: ^1.15.0
