name: geojson2h3
description: The geojson2h3 library includes a set of utilities for conversion between GeoJSON polygons and H3 hexagon indexes, using h3. Inspired by JS library geojson2h3.
version: 0.6.0-dev.1
homepage: https://github.com/festelo/h3_dart

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  h3_common: ^0.6.0-dev.1

dev_dependencies:
  test: ^1.21.2
  lints: ^2.0.0
  mockito: ^5.2.0
  build_runner: ^2.1.11
